name: build-toolchains
on:
  push:
    tags:        
      - 'v*'
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: builder/
          push: true
          tags: ghcr.io/londonhackspace/acnode-toolchain-builder:latest
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create -p ${GITHUB_REF##*/}
  build-linux:
    needs: build-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/londonhackspace/acnode-toolchain-builder:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp linux-config .config
          chmod 777 . -R
          su builder -c "ct-ng build"
          cd /home/builder/x-tools/arm-none-eabihf/
          tar -cjf ${GITHUB_WORKSPACE}/toolchain-linux.tar.bz2 *
          cd ${GITHUB_WORKSPACE}
          gh release upload ${GITHUB_REF##*/} ${GITHUB_WORKSPACE}/toolchain-linux.tar.bz2
  build-windows:
    needs: build-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/londonhackspace/acnode-toolchain-builder:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp windows-config .config
          chmod 777 . -R
          su builder -c "ct-ng build"
          cd /home/builder/x-tools/HOST-x86_64-w64-mingw32/arm-none-eabihf/
          zip -r ${GITHUB_WORKSPACE}/toolchain-windows.zip *
          cd ${GITHUB_WORKSPACE}
          gh release upload ${GITHUB_REF##*/} ${GITHUB_WORKSPACE}/toolchain-windows.zip
