name: build-dockerfile
on: [push]
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: builder/
          push: true
          tags: ghcr.io/londonhackspace/acnode-toolchain-builder:latest
  build-linux:
    needs: build-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/londonhackspace/acnode-toolchain-builder:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp linux-config .config
          chmod 777 . -R
          su builder -c "ct-ng build"
          cd /home/builder/x-tools/arm-none-eabi/
          tar -cjf ${GITHUB_WORKSPACE}/toolchain-linux.tar.bz2
          gh release create latest ${GITHUB_WORKSPACE}/toolchain-linux.tar.bz2